sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
  - 2.13.0
  - 2.12.6
  - 2.11.12

jdk:
  - oraclejdk8
  - openjdk8